\documentclass[preprint, 3p, authoryear]{elsarticle} %review=doublespace preprint=single 5p=2 column
%%% Begin My package additions %%%%%%%%%%%%%%%%%%%

\usepackage[hyphens]{url}

  \journal{Journal of Archaeological Science: Reports} % Sets Journal name

\usepackage{graphicx}
%%%%%%%%%%%%%%%% end my additions to header

\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
% TODO: Currently lineno needs to be loaded after amsmath because of conflict
% https://github.com/latex-lineno/lineno/issues/5
\usepackage{lineno} % add
  \linenumbers % turns line numbering on
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \usepackage{fontspec}
  \ifxetex
    \usepackage{xltxtra,xunicode}
  \fi
  \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
  \newcommand{\euro}{€}
\fi
% use microtype if available
\IfFileExists{microtype.sty}{\usepackage{microtype}}{}
\usepackage[]{natbib}
\bibliographystyle{plainnat}

\usepackage{graphicx}
\ifxetex
  \usepackage[setpagesize=false, % page size defined by xetex
              unicode=false, % unicode breaks when used with xetex
              xetex]{hyperref}
\else
  \usepackage[unicode=true]{hyperref}
\fi
\hypersetup{breaklinks=true,
            bookmarks=true,
            pdfauthor={},
            pdftitle={Insights into agricultural practices at the Phoenician site of Castro Marim between 7th -- 5th century BCE},
            colorlinks=false,
            urlcolor=blue,
            linkcolor=magenta,
            pdfborder={0 0 0}}

\setcounter{secnumdepth}{5}
% Pandoc toggle for numbering sections (defaults to be off)


% tightlist command for lists without linebreak
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

% From pandoc table feature
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}



\usepackage{subfig}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}



\begin{document}


\begin{frontmatter}

  \title{Insights into agricultural practices at the Phoenician site of Castro Marim between 7\textsuperscript{th} -- 5\textsuperscript{th} century BCE}
    \author[Universidade de Évora,Laboratório HERCULES,Sapienza Università di Roma]{Roshan Paladugu%
  %
  \fnref{1}}
   \ead{rpaladugu@uevora.pt} 
    \author[Sapienza Università di Roma]{Alessandra Celant%
  %
  \fnref{2}}
   \ead{alessandra.celant@uniroma1.it} 
    \author[Sapienza Università di Roma]{Federico Di Rita%
  %
  \fnref{2}}
   \ead{federico.dirita@uniroma1.it} 
    \author[Universidade de Lisboa]{Ana Margarida Arruda%
  %
  \fnref{2}}
   \ead{ana2@campus.ul.pt} 
    \author[Universidade de Lisboa]{Elisa de Sousa%
  %
  \fnref{2}}
   \ead{e.sousa@campus.ul.pt} 
    \author[Universidade de Évora,Laboratório HERCULES]{Anne-France Maurer%
  %
  \fnref{2}}
   \ead{annefrance.maurer@gmail.com} 
    \author[Sapienza Università di Roma]{Donatella Magri%
  %
  \fnref{2}}
   \ead{donatella.magri@uniroma1.it} 
    \author[Universidade de Évora,Laboratório HERCULES]{Cristina Barrocas Dias%
  %
  \fnref{1}}
   \ead{cmbd@uevora.pt} 
      \affiliation[Universidade de Évora]{Departamento de Química, Escola de Ciências e Tecnologia, Universidade de Évora, Colégio Luís António Verney, Rua Romão Ramalho 59, Évora, Portugal (7000-671)}
    \affiliation[Laboratório HERCULES]{Laboratório HERCULES, Universidade de Évora, Palácio do Vimioso, Largo Marquês de Marialva 8, 7000-554 Évora, Portugal}
    \affiliation[Sapienza Università di Roma]{Dipartimento di Biologia Ambientale, Sapienza Università di Roma, Piazzale A. Moro 5, 00185 Roma, Italy}
    \affiliation[Universidade de Lisboa]{Centro de Arqueologia da Universidade de Lisboa, Faculdade de Letras da Universidade de Lisboa, Alameda da Universidade, 1600-214, Lisboa, Portugal}
    \cortext[cor1]{Corresponding author}
    \fntext[1]{Corresponding Author}
    \fntext[2]{Equal contribution}
  
  \begin{abstract}
  Castro Marim is an Iron Age site from the Algarve region, Portugal. The earliest evidence of settlement, from the Late Bronze Age, dates to the 9\textsuperscript{th} century BCE, with the Phoenician-Punic period dating from the 7\textsuperscript{th} to the 3\textsuperscript{rd} century BCE. This study focuses on the stable isotope analysis of plant and collagen of faunal remains to reconstruct the cultivation and husbandry practices. Barley was the most abundantly cultivated cereal crop. The stable isotope results of barley indicate that it depended primarily on natural precipitation with a certain intensity of manuring. The differences from stable isotope data of domesticated fauna indicate a diverse management strategy for different species based on their economic importance and to capitalize from the animal by-products such as wool and dairy products.
  \end{abstract}
    \begin{keyword}
    Archaeobotany \sep Zooarchaeology \sep Agriculture \sep Portugal \sep 
    Iron Age
  \end{keyword}
  
 \end{frontmatter}

\section{Introduction}\label{introduction}

Southern Portuguese coast underwent Oriental colonization originating from the Near East during the 9\textsuperscript{th} century BCE. These colonizers, referred to as Phoenicians, were mostly culturally homogeneous and politically independent city-states with the Levant's power nucleus (present-day Lebanon) \citep{aubet87, dietler09, gomes_arruda18, quinn19}. It is widely accepted that the main driving force behind this westward expansion was the need to establish a stable supply of metalliferous resources \citep{arruda09, aubet87, aubet01, eshel_etal19, markoe05}. Phoenicians, through the establishment of agreements and negotiations with the native communities, mined the Iberian Pyrite belt for silver, tin, lead, and copper in the early 8\textsuperscript{th} century BCE \citep{eshel_etal19, renzi_etal12, wood_etal19}. The intense and prolonged settlements along the Southern Portuguese coast cannot simply be explained by the quest for mineral sources, primarily because a considerable part of them are situated in locations with neither metallogenic minerals nor pre-existing indigenous settlements. Other factors influencing settlement density include agricultural resources \citep{wagner_alvar03, wagner_alvar89}, exploitation of marine resources (e.g., salt \citep{manfredi92}, Tyrrhenian Purple production \citep{uriel00}), timber \citep{treumann09, treumann98}, and labor force \citep{arrastio99, arrastio00}. Of all the motivating factors for the expansion, the agricultural practices are explored in this study. The Phoenician traders had to ensure stable sources of food for the population apart from the industrial activities. Southwestern Iberia has been noted for its rich mineral veins and abundant natural fertility, and the Phoenicians exploited this fertile landscape while actively transforming it, including cultivable land \citep{arruda03, arruda09, neville98, roller14}. While the Phoenician metal exploitation perspective has been studied, the agricultural aspects have received little attention so far.

This study aims to shed light on the farming strategies and animal husbandry practices in the Phoenician -- Punic period of Portugal, specifically at Castro Marim. Botanical analysis of charred plant remains was performed to throw light on the plant species (both cultivated and wild) used by the Phoenicians. The analysis revealed the exploitation of non-cultivated species along with the cultivation of cereals and pulses. Carbon and nitrogen stable isotope analyses are used to reconstruct watering regimes and manuring practices in case of botanical remains. The faunal isotope data (\(\delta ^{13}C\), \(\delta ^{15}N\), and \(\delta ^{34}S\)) was used to illuminate past animal management strategies.

\section{Context}\label{context}

\subsection{Phoenician - Punic agriculture}\label{phoenician---punic-agriculture}

Most knowledge about Phoenician and Punic agriculture comes from the famous treaty by Mago, of which only a few fragments have survived and subsequently translated \citep{martin71}. Other accounts are by authors from the Greek and Roman domains, usually written centuries after the pinnacle of the Phoenician -- Punic horizon. The current understanding has been mainly developed due to systematic excavations of different Phoenician -- Punic settlements in Iberia and subsequent zooarchaeological and archaeobotanical studies on the recovered faunal and plant remains \citep{aubet01, wagner_alvar03, wagner_alvar89}. The Southwest Iberian region has been praised by Strabo (3, 2, 8) for possessing the rare combination of abundant mineral deposits and natural fertility \citep{roller14}. From the 9\textsuperscript{th} century BCE, the Phoenician presence is noted in the Iberian Peninsula along the Mediterranean and Atlantic coastal zone. This strategic location gave them reasonable access to the sailing routes and provided them with a plethora of cultivable land \citep{aubet01}. Colonies in Iberia were located in a landscape similar to that in the Levant with proximity to the coast and marked with steep mountain ranges and riverine valleys. Being located in a river valley gave the colonizers the ease of adapting existing practices from the Mediterranean in the Iberian hinterland. This included modifying and adapting the landscape to suit their agricultural needs, comprising farming and animal husbandry \citep{gomezbellard19}.

Agricultural techniques from the East, such as irrigation, were probably used to improve upon the native practices, at least in some areas. The iron production technology gave more robust implements such as plowshare, to the farmers. Better yielding cultivars (e.g., grapes and olives) and new species of animals (e.g., horse, donkey, and chicken) were introduced \citep{davis07, vanleeuwaarden_janssen85, queiroz_etal06}. Following the ``sixth century crisis'', in the period referred to as the Punic period, an economic change brought a drastic transformation in space use concerning both settlement and domain. In the latter phase of the Iron Age, in addition to the cultivation of cash crops and wine, local usable arboreal products such as timber and fruits were identified and exploited to boost exports \citep{gomezbellard19, neville98}. The exploitation of arboreal products and perennial crops meant the existence of both short-term and long-term agricultural investments. Such diverse investments with different harvest times must have led to the development of a complex agricultural economy.

\begin{figure*}
\includegraphics[width=0.98\textwidth]{C:/Users/rosha/Documents/R/Projects/castro_marim_phoenician/./images/castro_marim_map} \caption{Geological map of the region around Castro Marim on the banks of Guadiana River, Algarve Region of Portugal in EPSG 4326 projection. (Source: Directorate General of Mines and Geological Services - Carta de Geológica de Portugal).}\label{fig:castro-marim-loc}
\end{figure*}

\subsection{Site background}\label{site-background}

Castro Marim is located on the Guadiana estuary (Fig. \ref{fig:castro-marim-loc}) as a portal to the metallogenic mineral-rich Baixo -- Alentejo region as well as to the fertile cultivable lands in the interior regions. The Iron Age settlement was located on an elevation with adequate natural defensive elements and overlooked vast swatches of land, which allowed domination of estuarine traffic and agricultural activities in its domain of influence. These conditions allowed trade and cultural networks between the indigenous communities and the Mediterranean communities to flourish. The earliest Iron Age occupation of the site is characterized by East-West orthogonal settlement architecture dating from the first half of 7\textsuperscript{th} century BCE, in the Orientalising period \citep{arruda96, arruda_etal13}.This earliest Iron Age occupation corresponds to Castro Marim´s phase II (1\textsuperscript{st} half of the 7\textsuperscript{th} century BCE), III (2\textsuperscript{nd} half of the 7\textsuperscript{th} century BCE) and IV (6\textsuperscript{th} century BCE). Phoenician imports and other evidence for human presence declined from the second half of the 6th century BCE till the first half of the 5\textsuperscript{th} century BCE \citep{arruda96}. Significant changes in material culture and restructuring of the settlement architecture with a Northeast -- Southwest orientation are observed from the second half of the 5\textsuperscript{th} century BCE \citep{arruda_etal06, arruda_etal13, arruda_freitas08}. The earlier period's departure was marked by imports from Greek products -- specifically ceramics such as \emph{kilikes}, \emph{skyphoi}, and \emph{kantharoi} \citep{arruda97, arruda_etal20}. This resurgence put Castro Marim back in the main commercial circuits along the Iberian Peninsula's Atlantic coast till the 3\textsuperscript{rd} century BCE \citep{arruda00, arruda_etal06, arruda_etal13, sousa19}. The Phoenician -- Punic period is represented by archaeological phases III, IV, and V.

Being in a littoral zone made it possible to adopt a wide range of agricultural strategies and husbandry practices at Castro Marim. The presence of cereals (\emph{Hordeum} and \emph{Triticum}), grapes (\emph{Vitis vinifera/sylvestris}), pulses (\emph{Vicia} and \emph{Cicer}), and other cultivated species (\emph{Olea} and \emph{Coriandrum}), as well as the exploitation of wild woody plants (\emph{Pinus} and \emph{Arbutus} etc.) have been elucidated from the archaeological record \citep{queiroz_etal06}. Animals recovered from the excavation (native to Portugal) include cattle (\emph{Bos taurus}), goat (\emph{Capra hircus}), sheep (\emph{Ovis aries}), pig (\emph{Sus scrofa/domesticus}), red deer (\emph{Cervus elaphus}), and rabbit (\emph{Oryctolagus cuniculus}) \citep{davis07}. The arrival of chicken (\emph{Gallus domesticus}) has been documented, being introduced at least in the second half of 5\textsuperscript{th} century BCE \citep{davis07}.

\subsection{Environmental settings}\label{environmental-settings}



\begin{figure*}

{\centering \includegraphics[width=0.60\textwidth]{C:/Users/rosha/Documents/R/Projects/castro_marim_phoenician/./images/castro_marim_pal} 

}

\caption{Reconstruction of the Guadiana estuary during the Phoenician period based on geophysical and lithological data (adapted from \citet{wachsmann_etal09}).}\label{fig:castro-marim-pal}
\end{figure*}

Landscape surrounding during the Iron Age was quite different from what it is in modern times. Paleogeographic reconstruction based on geophysical and lithological data of the Guadiana estuary indicates muddy-bottom shallow estuarine setting at the mouth of the river during the Phoenician period, with the Iron Age settlement situated on a ridge projecting northward (Fig. \ref{fig:castro-marim-pal}) with a Pleistocene/mid-Holocene bedrock platform \citep{wachsmann_etal09}. After the arrival of Phoenicians (874 BCE), there was a decline in pinewood, \emph{Quercus} forest, and sclerophyllous thickets with an increase in scrub vegetation consisting of fire-adapted Cistaceae and Ericaceae \citep{fletcher_etal07}. This is due to prevailing warm and dry climatic conditions corresponding to a more arid regime across southern Iberia \citep{jalut_etal00, magny_etal02}.

\subsection{Archaeobotanical assessment}\label{archaeobotanical-assessment}

The original archaeobotanical assessment was carried out by \citet{queiroz_etal06}. Cereals make up the most significant fraction of the carpological remains. The bulk of cereals is barley (\emph{Hordeum vulgare}) with a tiny fraction of wheat (\emph{Triticum durum/aestivum}). Pulses are mainly broad beans (\emph{Vicia faba}) and chickpeas (\emph{Cicer arietinum}), of which the former has been present in Portugal since prehistoric times, whereas the latter was appreciated as a luxury food in the Roman period from Asia. The presence of grape (\emph{Vitis vinifera/sylvestris}) pips and charred wood is typical, starting from the Phoenician period in Portugal. The presence of grape pips in Iron Age Castro Marim indicates exploitation of wild vines or cultivated non-local vines by the local population. The most exciting carpological remains are of coriander (\emph{Coriandrum sativum}) which is not native to Portugal and was supposed to be introduced during medieval times, making this the earliest coriander occurrence in Portugal. Charred pine, oak, ash, and poplar wood were recovered abundantly. The exploitation of wild woody plants for timber and fruits marks the Phoenician colonization of the Iberian peninsula. Due to unforeseen circumstances, these identified remains could not be accessed for isotope analyses. Previously unprocessed sediments were studied again to gain plant remains.

\subsection{Zooarchaeological assessment}\label{zooarchaeological-assessment}

Ovicaprids (sheep and goats) followed by pigs and cattle dominate the Castro Marim mammal taxa \citep{davis07}. Both sheep and goats were equally represented with negligible fluctuations throughout the Iron Age at Castro Marim. The wild species in the assemblage consisted mainly of red deer and rabbits. Both the species (red deer and rabbits) are present consistently in all the phases of the settlement. It is worth mentioning here that no morphometric distinction could be made between wild and domesticated pigs. There is a spike in the presence of bird remains in the later phases of the Iron Age (Phase IV - V), primarily due to the introduction of domesticated chicken. The presence of partridge, a common wild species of Iberia, is also noted. Unlike the chicken, partridge has never been domesticated. Ovicaprids and cattle were kept well into maturity indicating that they were prized more for their secondary purposes than their meat. Sheep and goats were kept for their milk and wool, usually slaughtered after they reach at least two years of age. Cattle were valued for their power to plow in the fields as well as to pull heavy loads. Also, they too, were a source of milk. Pigs, on the other hand, were slaughtered as juveniles as they were primarily reared for meat. Most of the red deer found were adults, suggesting a hunting preference of that period as a vital subsidiary source of meat. Chicken seems to be slaughtered at a young age, whereas the partridges at an adult age. The slaughter age indicates the domesticated status of chicken and wild status of partridge, respectively.

\section{Principles of stable isotope analysis and ZooMS}\label{principles-of-stable-isotope-analysis-and-zooms}

\subsection{ZooMS analysis of ovicaprids}\label{zooms-analysis-of-ovicaprids}

Skeletal elements of goats and sheep are a common occurrence in archaeological contexts. A significant issue plaguing comparative husbandry studies between sheep and goats is the overlap of skeletal elements \citep{boessneck_etal64, payne69, schramm67}. Zooarchaeology through mass spectrometry applies peptide mass fingerprinting to identify archaeological remains \citep{buckley_etal09}. The main protein used for this is collagen, which is the most abundant protein in bone. Due to sequence differences in collagen of sheep and goat, ZooMS is able to differentiate between these two species, which is often not possible using standard morphological analysis \citep{buckley_etal10}.

\subsection{Stable isotope analysis of plants and animals}\label{stable-isotope-analysis-of-plants-and-animals}

Stable isotope (\(\delta ^{13}C\), and \(\delta ^{15}N\)) analyses of faunal bone collagen are valuable means of reconstructing foddering practices and other animal husbandry aspects \citep{price_etal17}. The variation in \(\delta ^{13}C\) of terrestrial organisms is determined by the primary producers' photosynthetic pathway, distinguished as C\textsubscript{3}, C\textsubscript{4}, and CAM plants \citep{deniro_epstein78, farquhar_etal89, kohn10, tieszen91}. Plant species are overwhelmingly C\textsubscript{3} in nature, including most cultivated plants such as barley, wheat, oats, and other wild edible plants \citep{fernandez-crespo_etal19}. C\textsubscript{4} plants consist primarily of tropical grasses, millets, sugarcane, corn, and sorghum. C\textsubscript{4} plants thrive in warm and high-temperature environments and thus are restricted to coastal zones in regions with temperate climates \citep{leegood13, price_etal17}. The analysis of faunal bones can help in determining whether these animals ate C3 or C4 plants, as there is an enrichment in \(\delta ^{13}C\) between diet and consumers (5\text{\textperthousand} for herbivores and 0-2\text{\textperthousand} between trophic levels \citep{bocherens_drucker03}). \(\delta ^{13}C\) measurements are also helpful to differentiate between terrestrial C\textsubscript{3} and aquatic food sources \citep{froehle_etal10, kellner_schoeninger07}.

\(\delta ^{15}N\) values indicate the trophic position (herbivore, omnivore, carnivore) of consumers in a food chain \citep{hedges_reynard07, price_etal17, schoeninger85}, with an enrichment between diet and consumer of around 3-5\text{\textperthousand} \citep{hedges_reynard07, schoeninger85}. \(\delta ^{15}N\) values can also be used to distinguish between terrestrial and marine diets \citep{deniro_epstein81, webb_etal17a}, and the consumption of manured, and unmanured crops \citep{bogaard_etal13, deniro_epstein81, fernandez-crespo_etal19, fraser_etal13a}. \(\delta ^{34}S\) of bone collagen from terrestrial species is often measured along with \(\delta ^{13}C\) and \(\delta ^{15}N\) to identify consumption of marine foods \citep{nehlich_etal10}.

The mean \(\delta ^{34}S\) value of terrestrial sources is assumed to be 0\text{\textperthousand} \citep{nehlich15}. Inorganic sulphur enters the food web through plants from the weathered bedrock (in a complete terrestrial setting), precipitation (sea spray), and microbial activity due to flooding events \citep{nitsch_etal19}. As the inorganic sulphur passes through the food web in the form of proteins, only a negligible fractionation occurs between diet and consumer \citep{hobson99, nehlich15}. Thus, the \(\delta ^{34}S\) ratio of collagen closely reflects that of the native water source, bedrock, and soluble sulphur-bearing minerals.

There are two significant inputs that humans can manipulate to cultivate plants: water and nitrogen input, which can be investigated using stable isotopes. Variation in \(\delta ^{13}C\) values of plants is primarily due to water availability as any dry spells affect the movement of carbon dioxide through the stomata \citep{ferrio_etal05, ferrio_etal07, fiorentino_etal15}. The water status of crops can be artificially controlled by irrigation regimes, reflected in \(\delta ^{13}C\) values \citep{ferrio_etal05, wallace_etal13}. \(\delta ^{13}C\) values measured in archaeological plants must be converted to carbon discrimination values to be compared with those of the modern crops grown under controlled watering regimes \citep{farquhar_etal89, wallace_etal13, coplen11}:

\[\Delta^{13}C = \frac{\delta ^{13}C_{air} - \delta ^{13}C_{plant}}{1+\delta ^{13}C_{plant}}\] Another major factor, which affects the \(\delta ^{13}C\) measurements of plants, is the canopy effect, where forested areas are more depleted in the heavier \textsuperscript{13}C isotope compared to open areas \citep{bonafini_etal13}. Thus, the \(\delta ^{13}C\) measurements of plants are the result of multiple factors and should be interpreted with caution.

One of the most ancient practices to increase soil fertility is by manuring with animal waste, as animal manure is much higher than endogenous soil in terms of nitrogen isotopic composition \citep{bogaard_etal13}. Usually, the plants treated with manure exhibit higher \(\delta ^{15}N\) values (as much as 10\text{\textperthousand}) when compared to unfertilized plants \citep{bogaard_etal07, fraser_etal11}. The \(\delta ^{13}C\) and \(\delta ^{15}N\) values themselves do not reveal the agricultural practices but reveal patterns when interpreted within a specific site.

\section{Materials and Methods}\label{materials-and-methods}

\subsection{Archaeobotanical analysis}\label{archaeobotanical-analysis}

200 grams of sediment from each stratigraphic layer of the excavation site was weighed and handpicked for plant macro remains (seeds/fruits and charcoal). The recovered remains were examined under a stereomicroscope and taxonomically identified (Table \ref{tab:table2}).

\subsection{Sample selection}\label{sample-selection}

Nine charred plant macro-remains (Table \ref{tab:table3}) of \emph{Hordeum vulgare} subsp. \emph{vulgare}, \emph{Hordeum vulgare} subsp. \emph{nudum}, and \emph{Pinus} sp. each as well as fifty faunal bone samples (Table \ref{tab:table4}) from conclusively adult individuals have been selected for this study. The sampled faunal bones represent the Phoenician -- Punic period of the settlement (phases III, IV, and V), whereas the charred plant macro -- remains are only from phase V due to the absence of plant remains from the older phases.

\subsection{Pretreatment of plant macro-remains}\label{pretreatment-of-plant-macro-remains}

In carbonized plant macro-remains, barley grain samples consist of at least ten whole grains, and pine samples consist of shell fragment. Morphologically intact samples were chosen after examination under a stereomicroscope (7-45x magnification) and removing any visibly adhering foreign contaminant. An acid-base-acid (ABA) treatment was applied as a pre-treatment \citep{bogaard_etal13, fraser_etal13a}. First, the samples were treated with 10 mL of 0.5 M HCl at 70 \(\text{\textdegree}\)C for 60 minutes (or until effervescing stops) and then rinsed with ultrapure water until a neutral pH was achieved. 10 mL of 0.1 NaOH solution was added to the samples at 70 \(\text{\textdegree}\)C for 60 minutes and then rinsed with ultrapure water to achieve a neutral pH. Finally, the samples were treated with 0.5 M HCl at 70 \(\text{\textdegree}\)C for 30-60 minutes, followed by three rinses with ultrapure water and subsequent freeze-drying.

\subsection{Collagen extraction}\label{collagen-extraction}

500 -- 700 mg of bone was cut using a DREMEL\(\text{\textregistered}\) rotary drill with a diamond disc and cleaned of dirt, discoloration, and other foreign content with a dental burr. Compact bone was sampled over spongy bone. The modified \citet{longin71} method was used to extract collagen from faunal bones pieces previously analysed with FTIR by demineralization \citep{richards_hedges99}. Approximately 600 mg of bone sample was demineralized using 0.5 M HCl at 4 \(\text{\textdegree}\)C for a fortnight with daily vortex and an acid change after 7 days. Repeated rinses with ultrapure water to reach neutral pH were performed, and the demineralized bones were subjected to an overnight treatment in 0.125 M NaOH at room temperature to remove fulvic and humic acid contamination. The samples were then rinsed repeatedly with ultrapure water to achieve neutrality and gelatinized in 0.01 M HCl at 70 \(\text{\textdegree}\)C for 48 hours. The impurities were separated by filtering the collagen-containing liquid fraction using Ezee -- Filter\(^\text{\texttrademark}\) filters (Elkay\(^\text{\textregistered}\) Laboratory Products). The solubilized collagen was frozen and subsequently lyophilized for 48 hours.

\subsection{ZooMS analysis}\label{zooms-analysis}

A small subsample of the extracted collagen was placed into a microfuge tube and 100 \(\mu\)L 50mM ammonium bicarbonate (AmBic) was added to the samples. The samples were digested overnight using 1 \(\mu\)L of 0.5 \(\mu\)g/\(\mu\)L porcine trypsin (Promega\(^\text{\textregistered}\), UK) at 37 \(\text{\textdegree}\)C and the digestion was stopped by the addition of trifluoroacetic acid (TFA) at a concentration of 0.5--1 \% of the total solution. The samples were desalted using C18 zip-tips \citep{vandoorn_etal11} and eluted using 100 \(\mu\)L of 50\% acetonitrile (ACN)/0.1 \% TFA (v/v). The zip-tipped samples were spotted in triplicate onto a MTP384 Bruker ground steel MALDI target plate; 1 \(\mu\)L of sample was pipetted onto each sample spot and then mixed with 1 \(\mu\)L of \(\alpha\)-cyano-4-hydroxycinnamic acid matrix solution (1 \% in 50 \% acetonitrile / 0.1 \% trifluoroacetic acid (v/v/v)).

The samples were analysed on a Bruker\(^\text{\textregistered}\) Ultraflex III\(^\text{\texttrademark}\) MALDI-ToF mass spectrometer. The resulting MS spectra were analysed using mMass \citep{strohalm_etal10} an Open Source mass spectrometry interpretation tool. The three spectra for each sample were averaged and the averaged spectrum was cropped between 800 and 3000 m/z and peak picking was carried out using a signal to noise ratio of 6. The resulting spectra were compared to a publicly available ZooMS database.

\subsection{Stable carbon and nitrogen isotope analysis}\label{stable-carbon-and-nitrogen-isotope-analysis}

An amount of 0.5 - 0.7 mg of freeze-dried collagen powder/barley grain samples were weighed in tin capsules and combusted in an elemental analyzer (EA) with oxygen (Flash 2000 HT\(^\text{\texttrademark}\), Thermo Fisher Scientific\(^\text{\textregistered}\), Bremen, Germany) using pure helium as carrier gas. Isotopic ratios were obtained on a Delta V Advantage Continuous Flow\(^\text{\texttrademark}\) -- Isotope Ratio Mass Spectrometer (Thermo Fisher Scientific\(^\text{\textregistered}\), Bremen, Germany). The raw machine output was normalised by a three-point calibration using international standard reference materials (SRM), namely IAEA-CH-6 (sucrose, \(\delta ^{13}C\) = -- 10.499\text{\textperthousand}), IAEA-600 (caffeine, \(\delta ^{13}C\) = -- 27.771\text{\textperthousand}; \(\delta ^{15}N\) = + 1\text{\textperthousand}), and IAEA-N-2 (ammonium sulphate, \(\delta ^{15}N\) = + 20.3\text{\textperthousand}) and in-house standard L-Alanine (\(\delta ^{13}C\) = -- 18.5\text{\textperthousand}; \(\delta ^{15}N\) = + 1.1\text{\textperthousand}). The standards were regularly (after eleven analyses) included in the analytical routine to correct for instrumental drifts. The isotope values are expressed in per mil (\text{\textperthousand}) relative to VPDB (Vienna Pee-Dee Belemnite) for carbon and AIR (Ambient Inhalable Reservoir) for nitrogen. Precision (u\textsubscript{(RW)}) for \(\delta ^{13}C\) and \(\delta ^{15}N\) was determined to be ± 0.107 and ± 0.175 respectively in the basis of repeated measurement of calibration standards and check standards. Accuracy (u\textsubscript{(bias)}) of \(\delta ^{13}C\) is ± 0.41 and that of \(\delta ^{15}N\) is ± 0.28. The total analytical uncertainty was determined to be ± 0.43 for \(\delta ^{13}C\) and ± 0.33 for \(\delta ^{15}N\). In order to correct for charring effect in plant remains, 0.11\text{\textperthousand} and 0.31\text{\textperthousand} were subtracted from their \(\delta ^{13}C\) and \(\delta ^{15}N\) values, respectively \citep{nitsch_etal15}. The fluctuations in \(\delta ^{13}C\) of the atmospheric CO\textsubscript{2} throughout the Holocene were considered while interpreting the stable carbon isotope ratios. The \(\delta ^{13}C\) of atmospheric CO\textsubscript{2} during the period in the study was approximated using the AIRCO\textsubscript{2}\_LOESS system, and then this value was used to compute the \(\delta ^{13}C\) discrimination of plants independent of the source CO\textsubscript{2} \citep{farquhar_etal82, ferrio_etal05}.

\subsection{Stable sulphur isotope analysis}\label{stable-sulphur-isotope-analysis}

The collagen samples were combusted with additional V\textsubscript{2}O\textsubscript{5} and an oxygen pulse (IsoPrime\(^\text{\texttrademark}\) Mass spectrometer, Elementar Analysensysteme GmbH\(^\text{\textregistered}\), Langenselbold, Germany). Calibration of \(\delta ^{34}S\) values was performed using international inorganic standards for stable sulphur isotope analysis: NBS127 (+20.3\text{\textperthousand}) and IAEA S1 (-0.3\text{\textperthousand}). B2155 protein (+6.96 ± 0.04\text{\textperthousand}) was used as an internal quality control standard. Stable sulphur isotope values are reported in parts per thousand relative to Vienna-Canyon Diablo Troilite (VCDT). The analysis was performed at SIIAF at the University of Lisbon.

\subsection{Statistical analysis}\label{statistical-analysis}

The obtained data were subjected to statistical analysis using R programming language \citep{rcoreteam20, wickham16}. Initially, means and standard deviations were calculated per species. Z-scores were calculated to detect the presence of outliers. Deviance from normal distribution was assessed using the Shapiro-Wilks test. F-tests were first used to check for significant equal variance, and subsequently, unpaired Student's t-tests were used for two-sample comparison since all the datasets were normally distributed.

\section{Reproducibility and open-source material}\label{reproducibility-and-open-source-material}

The R code and data used for the study can be accessed in the Supplementary Online Materials at \url{https://osf.io/gntzb/} for reproducibility and transparency. The code is released under the MIT license, the data as CC-0, and figures as CC-BY, to enable maximum re-use.

\section{Results}\label{results}

\subsection{Botanical Remains and their stable isotopes}\label{botanical-remains-and-their-stable-isotopes}

\begin{table}[!h]
\centering
\caption{\label{tab:table2}Recovered plant remains from archaeological sediments.}
\centering
\fontsize{7.5}{9.5}\selectfont
\begin{tabular}[t]{>{}lcc}
\toprule
Species & Quantity & Phase\\
\midrule
\em{Hordeum vulgare} & 1300 & V\\
\em{Triticum aestivum/durum} & 4 & V\\
\em{Apium graveolens} & 1 & V\\
\em{Pinus pinea} & 2 & V\\
\em{Brassica nigra} & 3 & V\\
\em{Pisum sativum} & 1 & V\\
\em{Galeopsis tetrahit} & 1 & V\\
\em{Vicia faba} & 2 & V\\
\bottomrule
\end{tabular}
\end{table}

No botanical remains could be recovered from the soil samples of phases I -- IV. The bulk of the recovered remains are from phase V representing the most mature chronological period of the occupation. Barley (\emph{Hordeum vulgare}) is the dominant taxon in the botanical record (Table \ref{tab:table2}). \emph{Hordeum vulgare} var. \emph{nudum} and \emph{Hordeum vulgare} subsp. \emph{vulgare} (Fig. \ref{fig:castro-archbot-assemblage} \textbf{(f)} and \textbf{(g)}, respectively) are the two cultivars that constitute the barley fraction with equal abundance. Wheat (\emph{Triticum aestivum/durum}) is the second most abundant taxon after barley. Large-scale cereal cultivation has been observed in sites located in river valleys near the South Iberian sea coast (including, Castillo de Doña Blanca in Guadalquivir Valley and El Villar in Guadalhorce Valley) \citep{semmler90, semmler92}, two sites which are located in similar geographical settings to Castro Marim). Cereal cultivation seems to be a significant activity, implying that cereals were the principal source of carbohydrates for both humans and animals. The greater presence of barley compared to wheat can be a strategy of `minimum returns on investment' against dry climatic conditions exploiting the fact that barley has a higher tolerance to drier conditions than wheat \citep{riehl09}. Two taxa of pulses have been noted, namely, peas (\emph{Pisum sativum}) and broad bean (\emph{Vicia faba}) (Fig. \ref{fig:castro-archbot-assemblage} \textbf{(d)} and \textbf{(i)} respectively). Pulses serve as a rich source of proteins and act as an alternative to animal-sourced protein for humans. The combined cultivation of pulses with cereals helps to maintain adequate soil nitrogen levels, leading to sustainable and diverse production. The presence of black mustard (\emph{Brassica nigra}) (Fig. \ref{fig:castro-archbot-assemblage} \textbf{(a)}) has been recorded. Black mustard is a common species along the rocky Mediterranean coasts and has long found its place as a culinary taste enhancer \citep{dixon06}. Like many members of \emph{Brassica}, black mustard was also used as a source of oil \citep{pena-chocarro_etal19}.



\begin{figure*}
\includegraphics[width=0.98\textwidth]{C:/Users/rosha/Documents/R/Projects/castro_marim_phoenician/./images/castro_bot_assemblage} \caption{Charred plant remains of settlement phase V from Castro Marim; \textbf{(a)} \emph{Brassica nigra}; \textbf{(b)} \emph{Apium graveolens}; \textbf{(c)} \emph{Galeopsis tetrahit}; \textbf{(d)} \emph{Pisum sativum}; \textbf{(e)} \emph{Triticum aestivum/durum}; \textbf{(f)} \emph{Hordeum vulgare} var. \emph{nudum}; \textbf{(g)} \emph{Hordeum vulgare} subsp. \emph{vulgare}; \textbf{(h)} \emph{Pinus pinea}; \textbf{(i)} \emph{Vicia faba}}\label{fig:castro-archbot-assemblage}
\end{figure*}

A fragment of a charred fruit has been attributed to \emph{Apium} taxon, suspected to be a seed of celery (\emph{Apium graveolens}) (Fig. \ref{fig:castro-archbot-assemblage} \textbf{(b)}). This attribution is done due to the presence of five slender longitudinal ridges on the surface of the fruit \citep{wilson16}.This species is native to the coastal Mediterranean region, considered to be its center of origin. The recorded use of celery as a vegetable in Europe is only from the 1600s, originating in Italy, gradually spreading westwards in the subsequent centuries \citep{tobyn_etal11}. The consumption of celery as a vegetable started in the Mediterranean region only around the 16\textsuperscript{th} century CE. In the Phoenician - Punic period, it could have been either cultivated or foraged as a medicinal herb rather than a food plant \citep{sturtevant86}. Shells of pine nuts (\emph{Pinus} sp.) (Fig. \ref{fig:castro-archbot-assemblage} \textbf{(h)}) are suspected to be from the species \emph{Pinus pinea}, commonly known as Mediterranean stone pine. Pine nut consumption has been documented in Portugal since the Palaeolithic period \citep{gale_carruthers00}. The stone pine nuts are high in protein and fat with low carbohydrates \citep{haws04}. The nuts are a valuable source of nutrition and could have been stored during low cultivated food production periods.





\begin{table*}

\caption{\label{tab:table3}\(\delta ^{13}C\) and \(\delta ^{15}N\) values of the charred plant macro-remains.}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\fontsize{7.5}{9.5}\selectfont
\begin{tabu} to \linewidth {>{\centering}X>{}c>{\raggedright}X>{\raggedright}X>{\raggedright}X>{\raggedright}X>{\raggedright}X>{\raggedright}X>{\centering}X}
\toprule
Sample ID & Species & \% C & \% N & $\delta^{13}C$  (\text{\textperthousand}) & $\delta^{15}N$ 
 (\text{\textperthousand}) & $\delta^{13}C_{cr}^{*}$ 
 (\text{\textperthousand}) & $\delta^{15}N_{cr}^{*}$ 
 (\text{\textperthousand}) & $\Delta^{13}C$ 
 (\text{\textperthousand})\\
\midrule
CMHV1 & \em{Hordeum vulgare {\normalfont subsp.} vulgare} & 37.7 & 2.1 & -22.1 & 9.6 & -22.2 & 9.3 & 16.1\\
CMHV2 & \em{Hordeum vulgare {\normalfont subsp.} vulgare} & 49.7 & 2.8 & -22.6 & 9.4 & -22.7 & 9.1 & 16.6\\
CMHV3 & \em{Hordeum vulgare {\normalfont subsp.} vulgare} & 50.0 & 2.2 & -24.7 & 9.1 & -24.8 & 8.8 & 18.8\\
CMHN1 & \em{Hordeum vulgare {\normalfont var.} nudum} & 49.1 & 3.6 & -23.0 & 8.9 & -23.1 & 8.6 & 17.0\\
CMHN2 & \em{Hordeum vulgare {\normalfont var.} nudum} & 49.5 & 3.9 & -23.2 & 8.4 & -23.3 & 8.1 & 17.2\\
CMHN3 & \em{Hordeum vulgare {\normalfont var.} nudum} & 47.6 & 2.6 & -23.1 & 9.8 & -23.2 & 9.5 & 17.1\\
CMPP1 & \em{Pinus pinea} & 58.8 & 0.7 & -25.5 & 11.4 & -25.6 & 11.1 & 19.6\\
CMPP2 & \em{Pinus pinea} & 48.3 & 0.8 & -24.7 & 11.3 & -24.8 & 11.0 & 18.8\\
CMPP3 & \em{Pinus pinea} & 56.7 & 0.6 & -25.4 & 13.8 & -25.5 & 13.5 & 19.5\\
\bottomrule
\multicolumn{9}{l}{\rule{0pt}{1em}\textsuperscript{*} \(\delta ^{13}C\) and \(\delta ^{15}N\) values corrected for charring effect.}\\
\end{tabu}}
\end{table*}

Table \ref{tab:table3} shows the results of stable isotope ratios of the two barley cultivars and stone pine and Table \ref{tab:table5} shows their mean summary. In the case of barley, the isotope ratios fall within the established predicted ranges obtained from experimentally charred modern cereals \citep{fraser_etal13a}. Since the isotope ratios of the stone pine are similar to that of barley, they are considered consistent.

\subsection{Collagen quality and ZooMS}\label{collagen-quality-and-zooms}

Collagen yields range between 2.5\% to 49.1\% (Table \ref{tab:table4}). Collagen extraction was considered successful for all the bone samples, based on published criteria, with carbon content between 15.3\% and 47.0\% \citep{ambrose90}, nitrogen content between 5.5\% and 17.3\% \citep{ambrose90}, C/N values between 3.15 and 3.50 (conservative upper limit with 0.5\% tolerance) \citep{guiry_szpak21}, C/S values between 300\% and 900\% \citep{nehlich_richards09}, and collagen yields greater than 1\% \citep{vanklinken99}. The extracted bone collagen samples exhibit C/N values ranged between 3.1 and 3.5 and C/S values between 225.9 and 688.4. Carbon and nitrogen amounts range from 20.3\% to 50.0\% and 7.3\% and 18.1\% respectively. All the faunal samples exhibited collagen quality parameters indicative of good preservation.
Sheep and goat samples were successfully distinguished on the basis of ZooMS. The identified sample entries are in bold format (Table \ref{tab:table4}).

\subsection{Faunal bone collagen isotope values}\label{faunal-bone-collagen-isotope-values}

All fifty faunal samples, demonstrate stable isotope values within the range expected for a C\textsubscript{3} temperate ecosystem with \(\delta ^{15}N\) and \(\delta ^{34}S\) values of fauna ranging from 2.9 \text{\textperthousand} to 17.3 \text{\textperthousand} and 9.5 \text{\textperthousand} to 15.8 \text{\textperthousand} respectively. The isotope composition of the fauna is presented in Table \ref{tab:table4} and the mean summary data by species in Table \ref{tab:table5}.






\begingroup\fontsize{7.5}{9.5}\selectfont

\begin{longtable}[t]{cccccccc}
\caption{\label{tab:table5}Summary of mean \(\delta ^{13}C\), \(\delta ^{15}N\), and \(\delta ^{34}S\) values, by species.}\\
\toprule
\multicolumn{2}{c}{ } & \multicolumn{2}{c}{\(\delta ^{13}C (\text{\textperthousand})\)} & \multicolumn{2}{c}{\(\delta ^{15}N (\text{\textperthousand})\)} & \multicolumn{2}{c}{\(\delta ^{34}S (\text{\textperthousand})\)} \\
\cmidrule(l{3pt}r{3pt}){3-4} \cmidrule(l{3pt}r{3pt}){5-6} \cmidrule(l{3pt}r{3pt}){7-8}
Species & n & $(\bar{x})$ & $(\sigma)$ & $(\bar{x})$ & $(\sigma)$ & $(\bar{x})$ & $(\sigma)$\\
\midrule
Cattle & 9 & -20.70 & 0.89 & 6.56 & 1.91 & 11.42 & 3.27\\
Chicken & 12 & -18.55 & 0.84 & 9.81 & 0.90 & 14.51 & 1.26\\
Goat & 7 & -19.69 & 0.37 & 4.96 & 0.92 & 12.32 & 1.99\\
Partridge & 2 & -20.30 & 0.42 & 5.70 & 0.14 & 13.90 & 0.00\\
Pig & 7 & -19.63 & 0.81 & 9.23 & 2.04 & 13.07 & 1.66\\
Rabbit & 7 & -21.61 & 1.07 & 7.91 & 3.53 & 13.84 & 2.00\\
Red Deer & 7 & -19.97 & 0.19 & 3.67 & 0.49 & 15.50 & 0.85\\
Sheep & 9 & -19.96 & 1.11 & 6.67 & 1.60 & 11.51 & 3.84\\
Grey Plover & 1 & -14.90 & -- & 10.30 & -- & 9.50 & --\\
Kittiwake & 1 & -15.50 & -- & 13.90 & -- & 15.80 & --\\
Barley & 6 & -23.12 & 0.88 & 9.20 & 0.51 & -- & --\\
Stone Pine & 3 & -25.20 & 0.44 & 12.17 & 1.42 & -- & --\\
\bottomrule
\end{longtable}
\endgroup{}

\section{Discussion}\label{discussion}



\begin{figure}
\centering
\includegraphics{RPaladugu_Castro_files/figure-latex/iso-hord-plots-1.pdf}
\caption{\label{fig:iso-hord-plots}\textbf{(a).} Beeswarm plot showing \(\Delta ^{13}C\) values of barley cultivars where the area between the blue dashed lines represents `moderately-watered' condition with the `well-watered' condition being above the top blue line and `poorly-watered' condition being below the lower blue line, based on the study of modern crops in varying watering conditions \citep{wallace_etal13}. \(\Delta ^{13}C\) values of stone pine have been plotted as well for the sake of visualization. \textbf{(b).} Beeswarm plot showing the manuring status of barley cultivars with green shaded region representing 1 SD range of estimated wild herbivore forage value (calculated from subtraction 4 \text{\textperthousand} from red deer \(\delta ^{15}N\) mean ± 1 SD range).}
\end{figure}

\subsection{Water and nutrient nitrogen availability for vegetation}\label{water-and-nutrient-nitrogen-availability-for-vegetation}

The \(\delta ^{13}C\) means of both barley cultivars show no statistically significant difference (t-statistic: -0.04, degrees of freedom: 4, \emph{p}-value: 0.97). The \(\Delta ^{13}C\) values (Figure \ref{fig:iso-hord-plots} \textbf{(a)}) show barley cultivated in poor to moderate watering conditions, which would indicate that the plants have been dependent on natural precipitation with little or no artificial irrigation in an arid climatic regime \citep{fernandez-crespo_etal19, fletcher_etal07}. The authors acknowledge the fact that the `watering bands' construct established by \citep{wallace_etal13} has its own limitations. However, in this study the \(\Delta ^{13}C\) isotope values of the plant remains are in agreement with the regional climatic regime data of Algarve \citep{fletcher_etal07}. This combined with the lack of any other contemporary ethnobotanical isotope data from the region justifies the use of watering bands.

There is no significant difference in \(\delta ^{15}N\) (t-statistic: 0.77, degrees of freedom: 4, \emph{p}-value: 0.49) between the two barley cultivars, but Pinus pinea yields higher \(\delta ^{15}N\) values (Table \ref{tab:table3}). The \(\delta ^{15}N\) mean values of C\textsubscript{3} plants near salt-marshes are higher when compared to coastal and inland sites \citep{cloern_etal02}. The stone pine samples exhibit higher mean values than the barley cultivars despite the possibility that the latter could be subjected to manuring regimes (Figure \ref{fig:iso-hord-plots} \textbf{(b)}) as they yield enriched \(\delta ^{15}N\) values compare to estimated wild herb forage values. This indicates that the barley was very likely cultivated in locations farther away from the coastline than the stone pine and explains their poor to moderate watering conditions despite Castro Marim being close to Guadiana estuary. Because the settlement was located on a narrow strip of land surrounded by water (Figure \ref{fig:castro-marim-pal}), the lack of space to grow crops could have been the primary reason for growing the barley away from the coast. The stone pine on the other hand seems to have been growing near the salt-marshes.

\begingroup\fontsize{7.5}{9.5}\selectfont

\begin{longtable}[t]{c>{}cccccccccc}
\caption{\label{tab:table4}Carbon, nitrogen, and sulphur isotope composition of the fauna.}\\
\toprule
Sample ID & Species & \% C & \% N & \% S & C:N & C:S & N:S & $\delta^{13}C (\text{\textperthousand})$ & $\delta^{15}N (\text{\textperthousand})$ & $\delta^{34}S (\text{\textperthousand})$\\
\midrule
\endfirsthead
\caption[]{\label{tab:table4}Carbon, nitrogen, and sulphur isotope composition of the fauna. \textit{(continued)}}\\
\toprule
Sample ID & Species & \% C & \% N & \% S & C:N & C:S & N:S & $\delta^{13}C (\text{\textperthousand})$ & $\delta^{15}N (\text{\textperthousand})$ & $\delta^{34}S (\text{\textperthousand})$\\
\midrule
\endhead

\endfoot
\bottomrule
\multicolumn{11}{l}{\rule{0pt}{1em}\textit{Note: }}\\
\multicolumn{11}{l}{\rule{0pt}{1em}The ovicaprid samples which were identified as goats and sheep are in bold.}\\
\endlastfoot
CMOF779 & \em{Pluvialis squatarola} & 40.8 & 14.8 & 0.3 & 3.2 & 375.9 & 81.6 & -14.9 & 10.3 & 9.5\\
CMOF777 & \em{Rissa tridactyla} & 40.9 & 15.1 & 0.3 & 3.2 & 376.9 & 109.7 & -15.5 & 13.9 & 15.8\\
CMOF756 & \em{Alectoris rufa} & 41.0 & 15.1 & 0.3 & 3.2 & 438.1 & 53.3 & -20.6 & 5.8 & 13.9\\
CMOF737 & \em{Alectoris rufa} & 40.6 & 14.9 & 0.3 & 3.2 & 416.8 & 49.0 & -20.0 & 5.6 & 13.9\\
CMOF710 & \em{Gallus domesticus} & 40.5 & 14.7 & 0.3 & 3.2 & 415.9 & 81.5 & -18.9 & 9.3 & 16.2\\
CMOF774 & \em{Gallus domesticus} & 40.7 & 14.9 & 0.2 & 3.2 & 452.9 & 74.4 & -20.2 & 7.8 & 15.1\\
CMOF750 & \em{Gallus domesticus} & 40.6 & 15.1 & 0.2 & 3.1 & 451.9 & 94.8 & -18.2 & 9.9 & 13.5\\
CMOF751 & \em{Gallus domesticus} & 40.6 & 14.8 & 0.2 & 3.2 & 515.8 & 106.5 & -18.1 & 9.8 & 14.9\\
CMOF772 & \em{Gallus domesticus} & 40.7 & 14.9 & 0.2 & 3.2 & 452.8 & 91.1 & -18.5 & 9.6 & 14.9\\
CMOF743 & \em{Gallus domesticus} & 41.1 & 15.0 & 0.2 & 3.2 & 498.4 & 100.2 & -18.1 & 9.6 & 12.5\\
CMOF746 & \em{Gallus domesticus} & 42.4 & 15.8 & 0.2 & 3.1 & 514.6 & 100.4 & -17.3 & 9.6 & 12.2\\
CMOF744 & \em{Gallus domesticus} & 43.4 & 16.0 & 0.3 & 3.2 & 429.3 & 80.1 & -17.5 & 9.5 & 14.7\\
CMOF731 & \em{Gallus domesticus} & 42.8 & 15.6 & 0.3 & 3.2 & 393.6 & 86.0 & -19.3 & 10.9 & 16.2\\
CMOF730 & \em{Gallus domesticus} & 50.0 & 18.1 & 0.2 & 3.2 & 606.3 & 115.5 & -19.6 & 11.1 & 14.1\\
CMOF709 & \em{Gallus domesticus} & 42.8 & 15.7 & 0.2 & 3.2 & 544.0 & 119.8 & -18.7 & 11.0 & 14.6\\
CMOF745 & \em{Gallus domesticus} & 41.0 & 15.3 & 0.2 & 3.1 & 476.1 & 95.2 & -18.2 & 9.6 & 15.2\\
CMOF158 & \em{Sus domesticus} & 41.0 & 15.2 & 0.2 & 3.2 & 521.0 & 119.5 & -19.3 & 11.0 & 14.6\\
CMOF439 & \em{Sus domesticus} & 21.7 & 8.0 & -- & 3.2 & -- & -- & -19.8 & 8.8 & --\\
CMOF354 & \em{Sus domesticus} & 40.9 & 15.3 & 0.2 & 3.1 & 496.0 & 133.8 & -18.0 & 12.9 & 11.4\\
CMOF253 & \em{Sus domesticus} & 40.3 & 15.0 & 0.2 & 3.1 & 489.3 & 76.3 & -19.6 & 7.3 & 11.9\\
CMOF338 & \em{Sus domesticus} & 40.8 & 15.0 & -- & 3.2 & -- & -- & -20.3 & 8.5 & --\\
CMOF466 & \em{Sus domesticus} & 40.8 & 15.0 & 0.2 & 3.2 & 544.1 & 100.4 & -20.1 & 8.8 & 14.4\\
CMOF323 & \em{Sus domesticus} & 40.4 & 14.9 & -- & 3.2 & -- & -- & -20.3 & 7.3 & --\\
CMOF435 & \em{Bos taurus} & 41.1 & 14.9 & 0.2 & 3.2 & 477.5 & 88.9 & -20.2 & 8.9 & 10.3\\
CMOF370 & \em{Bos taurus} & 39.8 & 14.6 & 0.2 & 3.2 & 443.1 & 66.7 & -21.2 & 7.0 & 15.2\\
CMOF402 & \em{Bos taurus} & 41.8 & 15.8 & -- & 3.1 & -- & -- & -19.0 & 7.6 & --\\
CMOF201 & \em{Bos taurus} & 41.9 & 15.6 & 0.2 & 3.1 & 558.6 & 69.4 & -21.4 & 6.1 & 8.3\\
CMOF480 & \em{Bos taurus} & 39.1 & 14.4 & 0.2 & 3.2 & 580.6 & 52.5 & -21.7 & 4.1 & 15.3\\
CMOF147 & \em{Bos taurus} & 43.0 & 16.2 & -- & 3.1 & -- & -- & -20.0 & 7.2 & --\\
CMOF468 & \em{Bos taurus} & 40.9 & 15.5 & 0.2 & 3.1 & 642.4 & 122.8 & -21.6 & 9.1 & 11.6\\
CMOF393 & \em{Bos taurus} & 42.1 & 15.3 & -- & 3.2 & -- & -- & -20.3 & 3.9 & --\\
CMOF94 & \em{Bos taurus} & 36.7 & 13.9 & 0.2 & 3.1 & 490.4 & 58.0 & -20.9 & 5.1 & 7.8\\
\cellcolor{white}{\textcolor{black}{\textbf{CMOF397}}} & \em{\cellcolor{white}{\textcolor{black}{\textbf{Capra hircus}}}} & \cellcolor{white}{\textcolor{black}{\textbf{38.7}}} & \cellcolor{white}{\textcolor{black}{\textbf{14.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{0.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{3.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{688.4}}} & \cellcolor{white}{\textcolor{black}{\textbf{64.5}}} & \cellcolor{white}{\textcolor{black}{\textbf{-19.8}}} & \cellcolor{white}{\textcolor{black}{\textbf{4.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{10.9}}}\\
\cellcolor{white}{\textcolor{black}{\textbf{CMOF181}}} & \em{\cellcolor{white}{\textcolor{black}{\textbf{Capra hircus}}}} & \cellcolor{white}{\textcolor{black}{\textbf{41.3}}} & \cellcolor{white}{\textcolor{black}{\textbf{15.3}}} & \cellcolor{white}{\textcolor{black}{\textbf{0.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{3.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{580.4}}} & \cellcolor{white}{\textcolor{black}{\textbf{59.5}}} & \cellcolor{white}{\textcolor{black}{\textbf{-19.8}}} & \cellcolor{white}{\textcolor{black}{\textbf{4.9}}} & \cellcolor{white}{\textcolor{black}{\textbf{12.6}}}\\
\cellcolor{white}{\textcolor{black}{\textbf{CMOF420}}} & \em{\cellcolor{white}{\textcolor{black}{\textbf{Capra hircus}}}} & \cellcolor{white}{\textcolor{black}{\textbf{40.7}}} & \cellcolor{white}{\textcolor{black}{\textbf{15.1}}} & \cellcolor{white}{\textcolor{black}{\textbf{0.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{3.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{494.3}}} & \cellcolor{white}{\textcolor{black}{\textbf{59.4}}} & \cellcolor{white}{\textcolor{black}{\textbf{-19.3}}} & \cellcolor{white}{\textcolor{black}{\textbf{5.7}}} & \cellcolor{white}{\textcolor{black}{\textbf{13.6}}}\\
\cellcolor{white}{\textcolor{black}{\textbf{CMOF673}}} & \em{\cellcolor{white}{\textcolor{black}{\textbf{Capra hircus}}}} & \cellcolor{white}{\textcolor{black}{\textbf{20.3}}} & \cellcolor{white}{\textcolor{black}{\textbf{7.3}}} & \cellcolor{white}{\textcolor{black}{\textbf{0.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{3.3}}} & \cellcolor{white}{\textcolor{black}{\textbf{225.9}}} & \cellcolor{white}{\textcolor{black}{\textbf{51.9}}} & \cellcolor{white}{\textcolor{black}{\textbf{-19.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{5.4}}} & \cellcolor{white}{\textcolor{black}{\textbf{14.8}}}\\
\cellcolor{white}{\textcolor{black}{\textbf{CMOF660}}} & \em{\cellcolor{white}{\textcolor{black}{\textbf{Capra hircus}}}} & \cellcolor{white}{\textcolor{black}{\textbf{42.3}}} & \cellcolor{white}{\textcolor{black}{\textbf{15.6}}} & \cellcolor{white}{\textcolor{black}{\textbf{0.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{3.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{564.3}}} & \cellcolor{white}{\textcolor{black}{\textbf{48.5}}} & \cellcolor{white}{\textcolor{black}{\textbf{-19.8}}} & \cellcolor{white}{\textcolor{black}{\textbf{4.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{12.8}}}\\
\cellcolor{white}{\textcolor{black}{\textbf{CMOF14}}} & \em{\cellcolor{white}{\textcolor{black}{\textbf{Capra hircus}}}} & \cellcolor{white}{\textcolor{black}{\textbf{36.6}}} & \cellcolor{white}{\textcolor{black}{\textbf{13.1}}} & \cellcolor{white}{\textcolor{black}{\textbf{--}}} & \cellcolor{white}{\textcolor{black}{\textbf{3.3}}} & \cellcolor{white}{\textcolor{black}{\textbf{--}}} & \cellcolor{white}{\textcolor{black}{\textbf{--}}} & \cellcolor{white}{\textcolor{black}{\textbf{-20.3}}} & \cellcolor{white}{\textcolor{black}{\textbf{3.9}}} & \cellcolor{white}{\textcolor{black}{\textbf{--}}}\\
\cellcolor{white}{\textcolor{black}{\textbf{CMOF394}}} & \em{\cellcolor{white}{\textcolor{black}{\textbf{Capra hircus}}}} & \cellcolor{white}{\textcolor{black}{\textbf{27.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{10.0}}} & \cellcolor{white}{\textcolor{black}{\textbf{0.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{3.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{426.9}}} & \cellcolor{white}{\textcolor{black}{\textbf{85.7}}} & \cellcolor{white}{\textcolor{black}{\textbf{-19.6}}} & \cellcolor{white}{\textcolor{black}{\textbf{6.4}}} & \cellcolor{white}{\textcolor{black}{\textbf{9.2}}}\\
\cellcolor{white}{\textcolor{black}{\textbf{CMOF424}}} & \em{\cellcolor{white}{\textcolor{black}{\textbf{Ovis aries}}}} & \cellcolor{white}{\textcolor{black}{\textbf{40.6}}} & \cellcolor{white}{\textcolor{black}{\textbf{14.8}}} & \cellcolor{white}{\textcolor{black}{\textbf{0.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{3.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{493.1}}} & \cellcolor{white}{\textcolor{black}{\textbf{73.3}}} & \cellcolor{white}{\textcolor{black}{\textbf{-20.7}}} & \cellcolor{white}{\textcolor{black}{\textbf{7.0}}} & \cellcolor{white}{\textcolor{black}{\textbf{7.7}}}\\
\cellcolor{white}{\textcolor{black}{\textbf{CMOF374}}} & \em{\cellcolor{white}{\textcolor{black}{\textbf{Ovis aries}}}} & \cellcolor{white}{\textcolor{black}{\textbf{41.1}}} & \cellcolor{white}{\textcolor{black}{\textbf{15.3}}} & \cellcolor{white}{\textcolor{black}{\textbf{0.3}}} & \cellcolor{white}{\textcolor{black}{\textbf{3.1}}} & \cellcolor{white}{\textcolor{black}{\textbf{406.0}}} & \cellcolor{white}{\textcolor{black}{\textbf{68.4}}} & \cellcolor{white}{\textcolor{black}{\textbf{-17.3}}} & \cellcolor{white}{\textcolor{black}{\textbf{8.1}}} & \cellcolor{white}{\textcolor{black}{\textbf{13.4}}}\\
\cellcolor{white}{\textcolor{black}{\textbf{CMOF419}}} & \em{\cellcolor{white}{\textcolor{black}{\textbf{Ovis aries}}}} & \cellcolor{white}{\textcolor{black}{\textbf{36.8}}} & \cellcolor{white}{\textcolor{black}{\textbf{13.5}}} & \cellcolor{white}{\textcolor{black}{\textbf{0.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{3.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{516.5}}} & \cellcolor{white}{\textcolor{black}{\textbf{67.1}}} & \cellcolor{white}{\textcolor{black}{\textbf{-20.8}}} & \cellcolor{white}{\textcolor{black}{\textbf{5.6}}} & \cellcolor{white}{\textcolor{black}{\textbf{7.0}}}\\
\cellcolor{white}{\textcolor{black}{\textbf{CMOF463}}} & \em{\cellcolor{white}{\textcolor{black}{\textbf{Ovis aries}}}} & \cellcolor{white}{\textcolor{black}{\textbf{40.7}}} & \cellcolor{white}{\textcolor{black}{\textbf{15.3}}} & \cellcolor{white}{\textcolor{black}{\textbf{0.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{3.1}}} & \cellcolor{white}{\textcolor{black}{\textbf{543.5}}} & \cellcolor{white}{\textcolor{black}{\textbf{86.6}}} & \cellcolor{white}{\textcolor{black}{\textbf{-20.8}}} & \cellcolor{white}{\textcolor{black}{\textbf{7.6}}} & \cellcolor{white}{\textcolor{black}{\textbf{15.9}}}\\
\cellcolor{white}{\textcolor{black}{\textbf{CMOF656}}} & \em{\cellcolor{white}{\textcolor{black}{\textbf{Ovis aries}}}} & \cellcolor{white}{\textcolor{black}{\textbf{40.9}}} & \cellcolor{white}{\textcolor{black}{\textbf{15.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{0.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{3.1}}} & \cellcolor{white}{\textcolor{black}{\textbf{574.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{46.8}}} & \cellcolor{white}{\textcolor{black}{\textbf{-19.8}}} & \cellcolor{white}{\textcolor{black}{\textbf{3.9}}} & \cellcolor{white}{\textcolor{black}{\textbf{17.3}}}\\
\cellcolor{white}{\textcolor{black}{\textbf{CMOF260}}} & \em{\cellcolor{white}{\textcolor{black}{\textbf{Ovis aries}}}} & \cellcolor{white}{\textcolor{black}{\textbf{42.5}}} & \cellcolor{white}{\textcolor{black}{\textbf{15.9}}} & \cellcolor{white}{\textcolor{black}{\textbf{--}}} & \cellcolor{white}{\textcolor{black}{\textbf{3.1}}} & \cellcolor{white}{\textcolor{black}{\textbf{--}}} & \cellcolor{white}{\textcolor{black}{\textbf{--}}} & \cellcolor{white}{\textcolor{black}{\textbf{-19.8}}} & \cellcolor{white}{\textcolor{black}{\textbf{5.9}}} & \cellcolor{white}{\textcolor{black}{\textbf{--}}}\\
\cellcolor{white}{\textcolor{black}{\textbf{CMOF691}}} & \em{\cellcolor{white}{\textcolor{black}{\textbf{Ovis aries}}}} & \cellcolor{white}{\textcolor{black}{\textbf{40.9}}} & \cellcolor{white}{\textcolor{black}{\textbf{15.4}}} & \cellcolor{white}{\textcolor{black}{\textbf{0.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{3.1}}} & \cellcolor{white}{\textcolor{black}{\textbf{545.9}}} & \cellcolor{white}{\textcolor{black}{\textbf{106.4}}} & \cellcolor{white}{\textcolor{black}{\textbf{-20.7}}} & \cellcolor{white}{\textcolor{black}{\textbf{9.3}}} & \cellcolor{white}{\textcolor{black}{\textbf{12.4}}}\\
\cellcolor{white}{\textcolor{black}{\textbf{CMOF477}}} & \em{\cellcolor{white}{\textcolor{black}{\textbf{Ovis aries}}}} & \cellcolor{white}{\textcolor{black}{\textbf{43.9}}} & \cellcolor{white}{\textcolor{black}{\textbf{15.6}}} & \cellcolor{white}{\textcolor{black}{\textbf{0.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{3.3}}} & \cellcolor{white}{\textcolor{black}{\textbf{558.3}}} & \cellcolor{white}{\textcolor{black}{\textbf{61.0}}} & \cellcolor{white}{\textcolor{black}{\textbf{-19.5}}} & \cellcolor{white}{\textcolor{black}{\textbf{5.6}}} & \cellcolor{white}{\textcolor{black}{\textbf{8.8}}}\\
\cellcolor{white}{\textcolor{black}{\textbf{CMOF303}}} & \em{\cellcolor{white}{\textcolor{black}{\textbf{Ovis aries}}}} & \cellcolor{white}{\textcolor{black}{\textbf{42.1}}} & \cellcolor{white}{\textcolor{black}{\textbf{15.7}}} & \cellcolor{white}{\textcolor{black}{\textbf{0.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{3.1}}} & \cellcolor{white}{\textcolor{black}{\textbf{562.5}}} & \cellcolor{white}{\textcolor{black}{\textbf{80.0}}} & \cellcolor{white}{\textcolor{black}{\textbf{-20.2}}} & \cellcolor{white}{\textcolor{black}{\textbf{7.0}}} & \cellcolor{white}{\textcolor{black}{\textbf{9.6}}}\\
CMOF230 & \em{Oryctolagus cuniculus} & 40.9 & 14.9 & 0.3 & 3.2 & 436.8 & 43.3 & -21.6 & 4.7 & 16.7\\
CMOF254 & \em{Oryctolagus cuniculus} & 40.4 & 14.6 & 0.3 & 3.2 & 385.5 & 96.8 & -21.5 & 11.8 & 11.4\\
CMOF99 & \em{Oryctolagus cuniculus} & 42.9 & 14.4 & 0.2 & 3.5 & 602.2 & 99.9 & -20.5 & 8.3 & 14.3\\
CMOF457 & \em{Oryctolagus cuniculus} & 40.5 & 15.0 & 0.2 & 3.2 & 450.9 & 41.3 & -23.2 & 4.3 & 14.2\\
CMOF353 & \em{Oryctolagus cuniculus} & 42.7 & 15.8 & 0.2 & 3.2 & 495.4 & 110.2 & -21.0 & 11.1 & 12.6\\
CMOF334 & \em{Oryctolagus cuniculus} & 43.3 & 15.9 & -- & 3.2 & -- & -- & -20.6 & 11.2 & --\\
CMOF324 & \em{Oryctolagus cuniculus} & 43.9 & 15.4 & -- & 3.3 & -- & -- & -22.9 & 4.0 & --\\
CMOF388 & \em{Cervus elaphus} & 28.3 & 10.3 & 0.2 & 3.2 & 504.4 & 62.6 & -20.0 & 4.1 & 15.6\\
CMOF373 & \em{Cervus elaphus} & 41.3 & 15.2 & 0.2 & 3.2 & 524.5 & 39.8 & -20.0 & 3.6 & 16.3\\
CMOF677 & \em{Cervus elaphus} & 41.4 & 14.9 & 0.3 & 3.2 & 394.8 & 31.4 & -20.3 & 3.8 & 15.8\\
CMOF467 & \em{Cervus elaphus} & 34.4 & 12.8 & 0.2 & 3.1 & 539.9 & 59.3 & -20.0 & 4.4 & 14.3\\
CMOF508 & \em{Cervus elaphus} & 38.0 & 14.3 & -- & 3.1 & -- & -- & -20.0 & 3.5 & --\\
CMOF643 & \em{Cervus elaphus} & 42.8 & 15.9 & -- & 3.1 & -- & -- & -19.7 & 2.9 & --\\
CMOF504 & \em{Cervus elaphus} & 38.6 & 13.9 & -- & 3.2 & -- & -- & -19.8 & 3.4 & --\\*
\end{longtable}
\endgroup{}

\subsection{Stable isotopes of wild and domesticated fauna}\label{stable-isotopes-of-wild-and-domesticated-fauna}



\begin{figure*}
\includegraphics[width=0.98\textwidth]{RPaladugu_Castro_files/figure-latex/fauna-carbnitro-iso-plot-1} \caption{Plot showing mean \(\delta ^{13}C\) and \(\delta ^{15}N\) values (mean ± 1 SD range) of faunal bone collagen and botanical remains. The colour palette is produced with the Colorgorical web app \citep{gramazio_etal17}.}\label{fig:fauna-carbnitro-iso-plot}
\end{figure*}



\begin{figure*}
\includegraphics[width=0.98\textwidth]{RPaladugu_Castro_files/figure-latex/fauna-sulph-iso-plot-1} \caption{Plot showing mean \(\delta ^{15}N\) and \(\delta ^{34}S\) values (mean ± 1 SD range) of faunal bone collagen. The yellow lines mark the range while the arrow indicates the decreasing trend of \(\delta ^{34}S\) values as one moves inland away from the coast up to 30 km \citep{wakshal_nielsen82, mizota_sasaki96, nehlich15}.}\label{fig:fauna-sulph-iso-plot}
\end{figure*}

Red deer when compared to other fauna have similar \(\delta ^{13}C\) isotope values and lower \(\delta ^{15}N\) values and yield amongst highest \(\delta ^{34}S\) values well within the expected range for areas affected by sea-spray indicating that the foraging occurred in open forests near the coast. The mean \(\delta ^{13}C\) values of rabbits are significantly lower than those of red deer (t-statistic: -4.01, degrees of freedom: 12, \emph{p}-value: 0). This can be attributed to the rabbits' foraging ground level flora with high recycling of CO\textsubscript{2} and shade from the higher levels of the canopy in contrast with the red deer foraging at taller vegetation. Feeding in forested areas causes the \(\delta ^{13}C\) values to deplete due to the canopy effect \citep{bonafini_etal13}. The \(\delta ^{15}N\) values of rabbits are anomalous with a standard deviation spanning almost a trophic level (standard deviation of \(\delta ^{15}N\): 3.5\text{\textperthousand}). It can be observed from Fig. \ref{fig:fauna-carbnitro-iso-plot} that the rabbits consist of two distinct groups, one group with higher \(\delta ^{13}C\) and \(\delta ^{15}N\) values compared to the other (Figure \ref{fig:fauna-carbnitro-iso-plot}). The group of rabbits with higher \(\delta ^{15}N\) values correspondingly have lower \(\delta ^{34}S\) values (Fig. \ref{fig:fauna-sulph-iso-plot}) which confirms salt-marsh foraging \citep{guiry_etal21a} whereas the other group had more coastal foraging.

Goat mean \(\delta ^{13}C\) values are not significantly different from those of sheep (t-statistic: 0.61, degrees of freedom: 14, \emph{p}-value: 0.55). The slightly positive \(\delta ^{13}C\) values ovicaprids' indicate foraging in open forests. Sheep exhibit significantly higher \(\delta ^{15}N\) values than goats (t-statistic: 2.5, degrees of freedom: 14, \emph{p}-value: 0.03), demonstrating that sheep were foddered on food sourced from manured vegetation with the assumption of uniform coastal impact on all vegetation (Figure \ref{fig:fauna-carbnitro-iso-plot}). Sheep are superior to goats both in terms of secondary products and ease of management \citep{davis07, rutter02}. Owing to the more attached economic interests with sheep, it is natural to give food sourced from cultivated crops. Since proximity to the salt-marsh masks the increase of \(\delta ^{15}N\) (as seen in Figure \ref{fig:iso-hord-plots}) values caused by manuring in cultivated crops, the statistically significant difference of \(\delta ^{15}N\) between goats and sheep is likely due to the consumption of manured crops. The \(\delta ^{34}S\) values of the ovicaprids fall well within the expected range of herbivores foraging on vegetation affected by sea spray with no statistically significant difference between each other (t-statistic: -0.47, degrees of freedom: 12, \emph{p}-value: 0.65). The cattle have no significantly different (t-statistic: -1.57, degrees of freedom: 16, \emph{p}-value: 0.14) \(\delta ^{13}C\) isotope ratios when compared to sheep. Cattle also seem to have grazed in open areas similar to the sheep. The \(\delta ^{15}N\) isotope ratios of cattle are also significantly not different from sheep (t-statistic: 0.13, degrees of freedom: 16, \emph{p}-value: 0.9). Though significantly not different than sheep, the mean \(\delta ^{15}N\) values of cattle are slightly lower (Figure \ref{fig:fauna-carbnitro-iso-plot}). The \(\delta ^{34}S\) values of cattle are also very similar to that of the sheep (t-statistic: 0.05, degrees of freedom: 12, \emph{p}-value: 0.96). Most of the cattle bones are from adults, which indicates that they were used as a source of power and only slaughtered for meat towards the end of their lives \citep{davis07}. Since they were used for labour intense tasks, their diet could have a considerable amount of cultivated crop components. All the three isotopic values of sheep and cattle present the image that the two domesticates were treated in a very similar manner and highly valued. Four sheep, two cattle, and one goat (Fig. \ref{fig:fauna-sulph-iso-plot}) are the only specimens showing \(\delta ^{34}S\) values outside the range of sea spray effect, which might be indicative of their non-local origin. The slightly positive \(\delta ^{13}C\) and high \(\delta ^{15}N\) values of pigs reflect an omnivorous diet consisting of agricultural components and human food scraps similar to the Neolithic and Chalcolithic periods from Portugal \citep{waterman_etal16, zalaite_etal18}. The slightly more positive \(\delta ^{13}C\) values and \(\delta ^{34}S\) of the pigs, compare to cattle and sheep are likely due to presence of fish and shellfish (molluscs and crustaceans) in the human food scraps.

The \(\delta ^{13}C\) values (t-statistic: 2.8, degrees of freedom: 12, \emph{p}-value: 0.02) and \(\delta ^{15}N\) values (t-statistic: 6.26, degrees of freedom: 12, \emph{p}-value: \ensuremath{4\times 10^{-5}}) of chicken and partridge are significantly different. The \(\delta ^{34}S\) values of chicken and partridge on the other hand are not significantly different (t-statistic: 0.66, degrees of freedom: 12, \emph{p}-value: 0.52). Higher \(\delta ^{13}C\), \(\delta ^{15}N\), and \(\delta ^{34}S\) values of the chicken can be due to its domesticated status, and indicate a diet of human food scraps which have a marine component. Also, chicken eat insects alongside the human-provided food which can lead to an increase of \(\delta ^{15}N\) values. Usual partridge diet consists of arthropods, grass seeds, flowers, and weeds while they prefer foraging at the edges of agricultural fields \citep{green84} which can explain the higher \(\delta ^{15}N\) values in comparison with red deer. All the partridges recovered are adults, whereas the chickens constitute juvenile-adult mix, further indicative that the former were hunted for consumption.
Grey plover has a mean \(\delta ^{13}C\) value of -14.9\text{\textperthousand} and a mean \(\delta ^{15}N\) value of 10.3\text{\textperthousand}. Grey plovers are known to feed in muddy intertidal zones on insects (such as Coleoptera), polychaetes, molluscs, and crustaceans \citep{perez-hurtado_etal97}. The isotope values are consistent with a diet including both terrestrial and marine prey. The \(\delta ^{34}S\) value of grey plover is outside the range expected for a partial marine diet since estuarine and intertidal zones have depleted \(\delta ^{34}S\) isotope values \citep{nehlich15}. Kittiwake's diet consists of fish, marine invertebrates, and plankton \citep{bull_etal04}. Kittiwake has a mean \(\delta ^{13}C\) value of -15.5\text{\textperthousand}, mean \(\delta ^{15}N\) value of 13.9\text{\textperthousand}, and a mean \(\delta ^{34}S\) value of 15.8\text{\textperthousand}, as expected of a species with a marine diet.

Overall, the domesticated mammals are not above one trophic level (4\text{\textperthousand} \(\delta^{15}N\)) over the plants (both cultivated barley and stone pine) (Figure \ref{fig:fauna-carbnitro-iso-plot}). Inland Iron Age domesticated mammals have mean \(\delta ^{13}C\) values ranging between 21 - 23\text{\textperthousand} (for C\textsubscript{3} temperate ecosystem) and \(\delta ^{15}N\) mean values ranging between 3-5\text{\textperthousand} for herbivores and \textgreater{} 6\text{\textperthousand} for omnivores \citep{fernandez-crespo_etal19, hamilton_etal19, schulting_etal19, styring_etal17}. In comparison, the fauna at Castro Marim have similar \(\delta ^{13}C\) values and slightly higher \(\delta ^{15}N\) mean values. Apart from manuring, another reason for these slightly higher \(\delta^{15}N\) values could be due to the proximity of the site to the salt-marsh. Most of the Castro Marim \(\delta ^{34}S\) isotope values are well within the range of sea spray effect (Figure \ref{fig:fauna-sulph-iso-plot}). The large spread of the \(\delta ^{34}S\) values could be due to the foraging spaces being located away from the settlement (\textless{} 30 kms) since Iron Age Castro Marim settlement was short of foraging space (Figure \ref{fig:castro-marim-pal}). The few individuals not within the range can be considered as non-local.

It is complicated to reconstruct farming and animal husbandry practices using stable isotope approach in an estuarine setting with coastal, salt-marsh, and slightly inland ecosystems due to the existence of multiple isotope baselines.

\section{Conclusions}\label{conclusions}

The \(\Delta ^{13}C\) values of the two barley cultivars indicate a certain level of dependence on natural precipitation with little to no artificial irrigation. Based on the \(\Delta ^{13}C\) values, stone pine seems to have better watering status than the barley cultivars. The manuring of barley was masked by the high nitrogen nutrient soils of the salt marshes. The \(\delta ^{15}N\) ratios of the stone pine are elevated due to the proximity of salt marsh. The \(\delta ^{15}N\) values of stone pine are greater than those of the barley, indicating that the cultivation took place in locations far away from salt marsh which is evident from the absence of space near the settlement in Iron Age. Significant difference between the mean \(\delta ^{15}N\) values of sheep and goats can be due to manuring of cultivated crops. In the case of wild fauna, the \(\delta ^{13}C\) and \(\delta ^{34}S\) values of rabbits indicate foraging at ground level in closed settings, while those of red deer indicate grazing in coastal open forests. The \(\delta ^{15}N\) and \(\delta ^{34}S\) values of rabbits indicate two different groups, with one group foraging in salt-marshes and the other in a more coastal setting. Ovicaprid \(\delta ^{13}C\) and \(\delta ^{34}S\) values indicate foraging in open pastures in proximity to the estuary. Comparing the \(\delta ^{15}N\) ratios of sheep and goats show that the former was fed agricultural produce/by-products, which the latter lacked. The cattle also foraged in open coastal areas and had cultivated components in its diet similar to the sheep. Pigs exhibit \(\delta ^{13}C\) and \(\delta ^{15}N\) values consistent with an omnivorous diet. In the case of the seabirds, both grey plover and kittiwake exhibit \(\delta ^{13}C\), \(\delta ^{15}N\), and \(\delta ^{34}S\) values consistent with their diet. Chicken \(\delta ^{13}C\) and \(\delta ^{15}N\) values are reflective of its domesticated status with a mixture of C\textsubscript{3} plants, insects, and human food scraps (inclusive of fish, molluscs, and crustaceans). The \(\delta ^{15}N\) values of the fauna are not a trophic level above the presented plant isotope values, which can be because of different isotope baselines or these plants were not a part of the former's diet. The \(\delta ^{34}S\) values of most fauna indicate foraging near estuary (salt-marsh and coastline), indicative of a local origin. Goats, pigs, and chickens have a low range of \(\delta ^{34}S\) values due to penning in specific spaces. The \(\delta ^{34}S\) values of cattle and sheep have a more extensive range of values which could be due to wider foraging range or some individuals being of non-local origin.

This study is the first of its kind on Phoenician-Punic fauna from the Iberian Peninsula and provides a preliminary insight into the cultivation and husbandry practices in Castro Marim during the Iron Age.

\section{Acknowledgements}\label{acknowledgements}

This project has received funding from the European Union's Horizon 2020 research and innovation programme under the Marie Skłodowska-Curie grant agreement No.~766311. The ZooMS analysis was carried out by Samantha Presslee at BioArCh, University of York who gratefully acknowledges the use of the Ultraflex III MALDI-ToF/ToF instrument in the York Centre of Excellence in Mass Spectrometry. The centre was created thanks to a major capital investment through Science City York, supported by Yorkshire Forward with funds from the Northern Way Initiative, and subsequent support from EPSRC (EP/K039660/1; EP/M028127/1). The authors would like to thank Rui Parreira for providing access to the samples (Direção Regional de Cultura do Algarve, Faro).

\renewcommand\refname{References}
\bibliography{mybibfile.bib}


\end{document}
