---
title: "Castro Marim Isotope Plots"
author: "Roshan Paladugu"
date: "4/6/2022"
output:
    bookdown::pdf_book:
      keep_tex: true
      extra_dependencies: "subfig"
      citation_package: default
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(ggsci)
library(kableExtra)
library(knitr)
library(patchwork)
library(ggbeeswarm)
library(RColorBrewer)
library(stringr)
library(knitr)

knitr::opts_chunk$set(echo=FALSE, message = FALSE, error = FALSE, warning = FALSE)
```


```{r plotparam, include=FALSE}
df_iso_total <- here::here("./data/castro_iso_total.csv") %>%
  read_csv(col_names = TRUE)

df_iso_fauna_summ <- here::here("./data/castro_fauna_iso_summ.csv") %>%
  readr::read_csv(col_names = TRUE)


theme<-theme(panel.background = element_blank(),legend.background = element_blank(), legend.key.size = unit(0.3, 'cm'), legend.box.background = element_rect(colour = "black"), legend.position="right",legend.text = element_text(size=6),text = element_text(),legend.title=element_text(size=7),axis.title.x = element_text(size=8), axis.title.y = element_text(size=8), panel.border=element_rect(fill=NA),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),strip.background=element_blank(), axis.text.x=element_text(colour="black"),axis.text.y=element_text(colour="black"),axis.ticks=element_line(colour="black"),plot.margin=unit(c(1,1,1,1),"line"))

```


(ref:fauna-carbnitro-iso) Plot showing mean $\delta ^{13}C$ and $\delta ^{15}N$ values (mean ± 1 SD range) of faunal bone collagen.


```{r carbnitro, , dpi=600, echo=FALSE, dpi=600, fig.show="hold", fig.width=8, fig.height=6, fig.env='figure*', fig.cap= '(ref:fauna-carbnitro-iso)'}
iso_carbnitro_mean_plot <- ggplot(df_iso_total, aes(x=dC, y=dN, shape = as.factor(Common_Name), colour= as.factor(Common_Name))) +
  geom_point(size = 3, alpha = 0.3) + labs(x = expression(paste(delta^{13}, "C (\u2030 vs. VPDB)")), y = expression(paste(delta^{15}, "N (\u2030 vs. Air)")), shape = 'Species', colour = 'Species') + scale_shape_manual(values = c(17,15,16,17,15,16,17,15,16,17,16,17)) + scale_color_manual(values=c("#4749dc", "#00344d", "#25738b", "#e30293", "#b452a2", "#5866ad", "#4e052e", "#071576", "#158a2c", "#0b4512", "#637f4b", "#7d4400")) + scale_y_continuous(breaks=seq(2.5,16,1)) + scale_x_continuous(limits=c(-27,-13),breaks=seq(-27,-12,1)) + annotate("text", x = -25, y = 15.5, colour = "gray44" , size = 3, label = "Pure C3 feeders") + annotate("text", x = -18.5, y = 15.5, colour = "gray44" , size = 3, label = "Addition of C4 plants") + theme + geom_vline(xintercept = -21, color='gray62', linetype="dotted", size=1) + geom_point(data = df_iso_fauna_summ,size = 3, aes(x=meandC, y=meandN)) + geom_errorbar(data = df_iso_fauna_summ,aes(x=meandC, y=meandN,ymin=meandN-stddevdN, ymax=meandN+stddevdN), width=.1) + geom_errorbarh(data = df_iso_fauna_summ,aes(x=meandC, y=meandN,xmin=meandC-stddevdC, xmax=meandC+stddevdC), height=.1)

iso_carbnitro_mean_plot

```


(ref:fauna-carbsulph-iso) Plot showing mean $\delta ^{13}C$ and $\delta ^{34}S$ values (mean ± 1 SD range) of faunal bone collagen.


```{r carbsulph, , dpi=600, echo=FALSE, dpi=600, fig.show="hold", fig.width=8, fig.height=6, fig.env='figure*', fig.cap= '(ref:fauna-carbsulph-iso)'}
iso_carbsulph_mean_plot <- ggplot(df_iso_total, aes(x=dC, y=dS, shape = as.factor(Common_Name), colour= as.factor(Common_Name))) +
  geom_point(size = 3, alpha = 0.3) + labs(x = expression(paste(delta^{13}, "C (\u2030 vs. VPDB)")), y = expression(paste(delta^{34}, "S (\u2030 vs. VCDT)")), shape = 'Species', colour = 'Species') + scale_shape_manual(values = c(17,15,16,17,15,16,17,15,16,17,16,17)) + scale_color_manual(values=c("#4749dc", "#00344d", "#25738b", "#e30293", "#b452a2", "#5866ad", "#4e052e", "#071576", "#158a2c", "#0b4512", "#637f4b", "#7d4400")) + scale_y_continuous(breaks=seq(5,18,1)) + scale_x_continuous(limits=c(-27,-13),breaks=seq(-27,-12,1)) + theme + geom_point(data = df_iso_fauna_summ,size = 3, aes(x=meandC, y=meandS)) + geom_errorbar(data = df_iso_fauna_summ,aes(x=meandC, y=meandS,ymin=meandS-stddevdS, ymax=meandS+stddevdS), width=.1) + geom_errorbarh(data = df_iso_fauna_summ,aes(x=meandC, y=meandS,xmin=meandC-stddevdC, xmax=meandC+stddevdC), height=.1) + geom_rect(xmin=-24,xmax=-19,ymin=0.5,ymax=12,fill=NULL)

iso_carbsulph_mean_plot

```


(ref:fauna-nitrosulph-iso) Plot showing mean $\delta ^{15}N$ and $\delta ^{34}S$ values (mean ± 1 SD range) of faunal bone collagen.


```{r nitrosulph, , dpi=600, echo=FALSE, dpi=600, fig.show="hold", fig.width=8, fig.height=6, fig.env='figure*', fig.cap= '(ref:fauna-nitrosulph-iso)'}
iso_nitrosulph_mean_plot <- ggplot(df_iso_total, aes(x=dN, y=dS, shape = as.factor(Common_Name), colour= as.factor(Common_Name))) +
  geom_point(size = 3, alpha = 0.3) + labs(x = expression(paste(delta^{15}, "N (\u2030 vs. Air)")), y = expression(paste(delta^{34}, "S (\u2030 vs. VCDT)")), shape = 'Species', colour = 'Species') + scale_shape_manual(values = c(17,15,16,17,15,16,17,15,16,17,16,17)) + scale_color_manual(values=c("#4749dc", "#00344d", "#25738b", "#e30293", "#b452a2", "#5866ad", "#4e052e", "#071576", "#158a2c", "#0b4512", "#637f4b", "#7d4400")) + scale_y_continuous(breaks=seq(5,18,1)) + scale_x_continuous(limits=c(2.5,16),breaks=seq(2,16,1)) + theme + geom_point(data = df_iso_fauna_summ,size = 3, aes(x=meandN, y=meandS)) + geom_errorbar(data = df_iso_fauna_summ,aes(x=meandN, y=meandS,ymin=meandS-stddevdS, ymax=meandS+stddevdS), width=.1) + geom_errorbarh(data = df_iso_fauna_summ,aes(x=meandN, y=meandS,xmin=meandN-stddevdN, xmax=meandN+stddevdN), height=.1)

iso_nitrosulph_mean_plot

```


