---
title: "castrotable3"
author: "Roshan Paladugu"
date: "2024-04-16"
output:
  bookdown::html_document2
---


```{r global_options, include=FALSE, dev=c('png', 'pdf', 'svg', 'tiff')}
library(ggplot2)
library(dplyr)
library(readr)
library(here)
library(ggsci)
library(kableExtra)
library(knitr)
library(patchwork)
library(ggbeeswarm)
library(stringr)
library(grid)

options(kableExtra.auto_format = FALSE)
options(knitr.graphics.rel_path = FALSE)
opts_chunk$set(echo=FALSE, message = FALSE, error = FALSE, warning = FALSE)


```




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE)

df_iso_fauna <- here::here("./data/castro_iso_fauna.csv") |>
  readr::read_csv(col_names = TRUE)

```




```{r table4, echo=FALSE, results='asis'}
options(knitr.kable.NA = "--")

color.goat <- which(df_iso_fauna$Species == 'Capra hircus')
color.sheep <- which(df_iso_fauna$Species == 'Ovis aries')

df_iso_fauna %>%
  select(Sample, Species,percentC,percentN,percentS,CN,CS,NS, dC, dN, dS) %>%
  kable(caption = "Carbon, nitrogen, and sulphur isotope composition of the fauna.", digits = 2, booktabs = T, longtable = T, align = "ccccccccccc", format = "html", col.names=c("Sample ID","Species","% C","% N","% S","C:N","C:S","N:S", "δ^13^C (‰)","δ^15^N (‰)","δ^34^S (‰)")) %>%
  kable_styling(font_size = 10,full_width = TRUE) %>%
  row_spec(color.goat, bold = T, color = "black", background = "white") %>%
  row_spec(color.sheep, bold = T, color = "black", background = "white") %>%
  column_spec(2,italic = TRUE) %>%
  footnote(general = "The ovicaprid samples which were identified as goats and sheep through ZooMS are in bold.")
  
```